####################################################################################
#                                  Common                                          #
####################################################################################
server:
  # form data size
  tomcat:
    max-http-form-post-size: 20MB
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    path: /error
    # always | never
    include-stacktrace: never
    whitelabel.enabled: false

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
####################################################################################
#                                    DEFAULT                                       #
####################################################################################
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  profiles:
    active: local
  # swagger 3 path match
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        # [physical] snake case -> camel case
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # [logical]
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  session:
    store-type: jdbc